language: java
branches:
  only:
  - master
before_install: bash etc/travis-setup.sh
install: true
script: eval $TEST_CMD
after_script: heroku keys:remove $USER@`hostname`
env:
  global:
  - HATCHET_RETRIES=3
  - HATCHET_DEPLOY_STRATEGY=git
  - HATCHET_BUILDPACK_BASE="https://github.com/heroku/heroku-buildpack-java.git"
  - HATCHET_APP_LIMIT=20
  - SHUNIT_HOME="/tmp/shunit2-2.1.6"
  - secure: TxnRX5U4nvJJoN07IZ8J+ToRQI1r6aE059/Ixyff1tUWEKNam/S6wR1Ce2N1R5aqgCR2M5VDXkMlHaROU7aOzhAGDlJ98YT2bOLTAH3igZ4thBzKS/awmqs65uqiX9U6gmncrcNCitp5qXsZE5ObiHE+guuLdpDUouS3JEJio6E=
  matrix:
  - TEST_CMD='./mvnw verify'
  - TEST_CMD="/tmp/testrunner/bin/run -c ."
